out_dir: results
metric_best: mae
metric_agg: argmin
accelerator: cuda:0
mlflow:
  use: false
  project: Exp
  name: peptides-struct-GRIT-RRWP
wandb:
  use: false
  project: peptides-struct
dataset:
  format: OGB
  name: peptides-structural
  task: graph
  task_type: regression
  transductive: false
  node_encoder: true
  node_encoder_name: Atom
  node_encoder_bn: false
  edge_encoder: true
  edge_encoder_name: Bond
  edge_encoder_bn: false
posenc_RRWP:
  enable: true
  ksteps: 24
  nhops: 3
  add_identity: true
  add_node_attr: false
  add_inverse: false
train:
  mode: custom
  batch_size: 16
  eval_period: 1
  ckpt_period: 100
model:
  type: GritTransformer
  loss_fun: l1
  graph_pooling: mean
gt:
  layer_type: GritTransformer
  layers: 6
  n_heads: 16
  dim_hidden: 256
  dropout: 0.05
  attn_dropout: 0.2
  layer_norm: false
  batch_norm: true
  attn:
    clamp: 5.0
    act: relu
    full_attn: true
    edge_enhance: true
    O_e: true
    norm_e: true
    signed_sqrt: true
gnn:
  head: default
  layers_pre_mp: 0
  layers_post_mp: 2
  dim_inner: 256
  batchnorm: true
  act: relu
  dropout: 0.0
optim:
  clip_grad_norm: true
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
