
# Customized for the Open-Polymer Challenge based on zinc-GRIT-RRWP.yaml
out_dir: results
metric_best: mae
seed: 0
metric_agg: argmin
tensorboard_each_run: True
accelerator: "cuda:0"
mlflow:
  use: False
wandb:
  use: False
dataset:
  format: PyG-PolymerData  # Use the custom data loader for polymers
  name: PolymerData
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode
  # node_encoder_num_types will be determined by the loader
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  # edge_encoder_num_types will be determined by the loader
  edge_encoder_bn: False
posenc_RRWP:
  enable: True
  ksteps: 21
  nhops: 3
  add_identity: True
  add_node_attr: False
  add_inverse: False
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  enable_ckpt: True
  ckpt_best: True
  ckpt_clean: True
model:
  type: GritTransformer
  loss_fun: l1  # Use L1 loss as specified in the base config
  edge_decoding: dot
  graph_pooling: add
gt:
  layer_type: GritTransformer
  layers: 10
  n_heads: 8
  dim_hidden: 64
  dropout: 0.0
  layer_norm: False
  batch_norm: True
  update_e: True
  attn_dropout: 0.2
  attn:
    clamp: 5.
    act: 'relu'
    full_attn: True
    edge_enhance: True
    O_e: True
    norm_e: True
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 3
  dim_inner: 64
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 1e-3
  max_epoch: 200  # A more reasonable default for faster iteration
  num_warmup_epochs: 50
  scheduler: cosine_with_warmup
  min_lr: 1e-6
